### ISSUE TITLE
How to set the width of tooltip ?

### ISSUE THREAD

**Issue by abcddpro** [euvl/vue-js-popover#10]
```
<template>
    <div>
        <tooltip/>
        <div v-if="data_ready">
            <table class="vue_datatable " ref="table" :class="table_cls" :style="table_style">
                <thead id="tHead">
                    <tr>
                        <th v-for="(col ,index) of _cols" :style="col.style" v-popover:tooltip ="col.help">
                            <input v-if="col.title=='__select'&&multi==true" type="checkbox" v-model="allChecked">
                            <span v-else-if="col.title=='__select'&&select==true"></span>
                            <span v-else v-popover:tooltip ="col.help">{{col.title}}</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <div v-else>Loading</div>
    </div>
</template>
```
I want to set the width of tooltip to 0 when "col.help" don't exist (in other word, I want to make it invisible), so how can I do it ?
Besides, the "\<tooltip/\>" component won't work if it was placed inside "\<tr\>\</tr\>". I placed it on the top at last.

Thanks.

**Comment by euvl** [comment]
Hi @abcddpro,

Thanks for using the plugin. 

You might just use `v-if="col.help"` on the tooltip instead of setting it's width to 0. If you will still want to set width to 0, do `<tooltip :width="0"/>`

For available props in tooltip component, take a look here:
https://css-tricks.com/using-divs-inside-tables/

Putting stuff directly into <tr> will not work, it's not the plugin limitation, just how html works. 

You can find this tutorial useful: 
https://css-tricks.com/using-divs-inside-tables/

Cheers 👍
